DROP TABLE IF EXISTS DE_TAB_ListInventoryCommission;

DROP TABLE IF EXISTS DE_TAB_NomenclatureInventList;

DROP TABLE IF EXISTS DE_DOC_InventoryList;

DROP TABLE IF EXISTS DE_DOC_OrderCreationInventoryCommission;

DROP TABLE IF EXISTS DE_CTL_Nomenclatures;

DROP TABLE IF EXISTS DE_CTL_StorageUnits;

DROP TABLE IF EXISTS DE_CTL_Producers;

DROP TABLE IF EXISTS DE_CTL_Employees;

DROP TABLE IF EXISTS DE_CTL_StorageLocations;

DROP TABLE IF EXISTS DE_CTL_MyOrganizations;

DROP TABLE IF EXISTS DE_CTL_Positions;